[tool.poetry]
name = "giab-test"
version = "0.1.0"
description = ""
authors = ["David Lin"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pysam = "^0.23.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
